In [1]:
print("hello")

hello


In [2]:
import numpy as np
l=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l)
a=np.array(l)
print(a)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
