In [26]:
import numpy as np
l=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l)
a=np.array(l)
print(a)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [27]:
print(a.shape)

(2, 2, 3)


In [28]:
print(a.ndim)

3


In [29]:
print(a.itemsize)

8


In [30]:
print(a.size)

12


In [31]:
print(len(a))

2
