In [1]:
import numpy as np
l=[[1,7,5],[18,143,420],[69,96,999]]
a=np.array(l)
print(a)

[[  1   7   5]
 [ 18 143 420]
 [ 69  96 999]]


In [2]:
print(a.min())

1


In [3]:
print(a.max())

999


In [4]:
print(a.sum())

1758


In [5]:
print(a.mean())

195.33333333333334


In [ ]:
print(a.std(
    
))

310.16662188787063


In [ ]:
print(a.min(axis=0))
print(a.min(axis=1))

[1 7 5]
