In [1]:
import numpy as np
l=[[1,7,5],[18,143,420],[69,96,999]]
a=np.array(l)
print(a)

[[  1   7   5]
 [ 18 143 420]
 [ 69  96 999]]


In [2]:
print(a.min())

1


In [3]:
print(a.max())

999


In [ ]:
print(a.sum())