In [1]:
import numpy as np
l=[[1,7,5],[18,143,420],[69,96,999]]
a=np.array(l)
print(a)

[[  1   7   5]
 [ 18 143 420]
 [ 69  96 999]]


In [2]:
print(a.min())

1


In [3]:
print(a.max())

999


In [4]:
print(a.sum())

1758


In [5]:
print(a.mean())

195.33333333333334


In [ ]:
print(a.std(
    
))

310.16662188787063


In [8]:
print(a.min(axis=0))
print(a.min(axis=1))

[1 7 5]
[ 1 18 69]


In [9]:
print(a.max(axis=0))
print(a.max(axis=1))

[ 69 143 999]
[  7 420 999]


In [10]:
l=[10,20,30,40]
a=np.array(l)
print(a)
print(a.flags)

[10 20 30 40]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [11]:
a[1]=200
print(a)

[ 10 200  30  40]


In [ ]:
a.flags['WRITEABLE']=False
print(a.flags)
a[2]=300
print(a)


ValueError: assignment destination is read-only