In [2]:
import numpy as np
l1=[[1,2,3],[4,5,6]]
l2=[[1,2],[3,4]]
l3=[[5,6],[7,8]]
a1=np.array(l1)
a2=np.array(l2)
a3=np.array(l3)
print(a1)
print(a2)
print(a3)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
res1=a1.T
print(res1)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
res2=a1.swapaxes(0,1)
print(res2)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
res3=np.dot(a2,a3)
print(res3)

[[19 22]
 [43 50]]


In [6]:
l=[[1,2],[3,4]]
a1=np.array(l)
print(a1)

[[1 2]
 [3 4]]


In [7]:
a2=np.array(l,dtype=int)
print(a2)

[[1 2]
 [3 4]]


In [ ]:
a3=np.array(l,dtype=float)
print(a3)