In [ ]:
import numpy as np
l=[[10,20,30],[40,50,60],[70,80,90],[100,110,120]]
a=np.array(l)
print(a[0])
print(a[0][2])
print(a[:3,:2])
print(a[:,2])


[10 20 30]
30
[[10 20]
 [40 50]
 [70 80]]
[ 30  60  90 120]
[[ 10  20]
 [ 40  50]
 [ 70  80]
 [100 110]]


In [8]:
l=[1,2,5,6,7,8,9,3]
print(l[0:-1])

[1, 2, 5, 6, 7, 8, 9]


In [ ]:
print(a[...,0:-1])

[[ 10  20]
 [ 40  50]
 [ 70  80]
 [100 110]]
