In [1]:
import numpy as np
l=[10,20,30]
a=np.array(l)
print(a)

[10 20 30]


In [2]:
l1=range(10)
a1=np.array(l1)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a2=np.arange(10)
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
a3=np.arange(10,40)
print(a3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [5]:
a4=np.arange(10,60,5)
print(a4)

[10 15 20 25 30 35 40 45 50 55]


In [6]:
a5=np.linspace(0.2,0.3)
print(a5)

[0.2        0.20204082 0.20408163 0.20612245 0.20816327 0.21020408
 0.2122449  0.21428571 0.21632653 0.21836735 0.22040816 0.22244898
 0.2244898  0.22653061 0.22857143 0.23061224 0.23265306 0.23469388
 0.23673469 0.23877551 0.24081633 0.24285714 0.24489796 0.24693878
 0.24897959 0.25102041 0.25306122 0.25510204 0.25714286 0.25918367
 0.26122449 0.26326531 0.26530612 0.26734694 0.26938776 0.27142857
 0.27346939 0.2755102  0.27755102 0.27959184 0.28163265 0.28367347
 0.28571429 0.2877551  0.28979592 0.29183673 0.29387755 0.29591837
 0.29795918 0.3       ]


In [7]:
a6=np.linspace(0.2,0.5,5)
print(a6)

[0.2   0.275 0.35  0.425 0.5  ]


In [8]:
a7=np.zeros(3)
print(a7)

[0. 0. 0.]


In [9]:
a8=np.zeros((3,3))
print(a8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
a9=np.ones(5)
print(a9)

[1. 1. 1. 1. 1.]


In [11]:
a10=np.ones((5,3))
print(a10)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a11=np.zeros((3,5),dtype=int)
print(a11)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [13]:
a12=np.ones((5,3),dtype=str)
print(a12)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [16]:
a13=np.eye(3)
print(a13)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a14=np.diag([2,5,1])
print(a14)

[[2 0 0]
 [0 5 0]
 [0 0 1]]
